apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    name: my-deployment-labels
    type: my-deployement-type
spec:
  template:
    metadata:
      name: my-app
      labels:
        name: my-app-label
        type: sample-type
        app: my-app
    spec:
      containers:
        - name: my-app
          image: mrityunjaybiswas/maven-project:latest
  replicas: 3
  selector:
    matchLabels:
      app: my-app
