apiVersion: apps/v1
kind: ReplicaSet
metadata:
        name: demoapp-replicaset
        labels:
             app: demoapp
spec:        
	template:
		metadate:
			name: demoapp
			labels:
				app: demoapp
		spec:
			containers:
			- name: myapp
			  image: mrityunjaybiswas/maven-project
replicas: 2

---

apiVersion: apps/v1
kind: Service
metadata:
   name: demoapp-service
spec:
   type: NodePort
   ports:
     - targetPort: 80
	   port: 80
   selector:
     app: myapp
